### PR TITLE
Fix prettier eslint config

### LINKED ISSUE #162: Fix lint with latest prettier-plugin
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md

See e.g. https://github.com/kaliber5/ember-responsive-image/pull/167/commits/b9d12f0e6abe1014e9d9be6083c6e87ee73d4f2d

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #162 + #173

### CODE REVIEW

File: blueprints/@kaliber5/k5-ember-boilerplate/files/.prettierrc.js [hunk 1]
```diff
@@ -0,0 +1,6 @@
+'use strict';
+
+module.exports = {
+  singleQuote: true,
+  printWidth: 120,
```
Comment (lolmaus) [inline blueprints/@kaliber5/k5-ember-boilerplate/files/.prettierrc.js:5]: Can we please switch to 100 chars per line?

I had got your approval on this previously, but that probably was for a single project and did not propagate for the boilerplate.

Fewer chars per line lets me open more panes in the IDE, improving my efficiency.

EmberJS [has 100](https://github.com/emberjs/ember.js/blob/master/.prettierrc.js#L6), and Prettier default [is even smaller](https://prettier.io/docs/en/options.html#print-width).

**Review by lolmaus — CHANGES_REQUESTED** [review]

File: blueprints/@kaliber5/k5-ember-boilerplate/files/.prettierrc.js (hunk 1 above)
Comment (simonihmig) [reply blueprints/@kaliber5/k5-ember-boilerplate/files/.prettierrc.js]: Done
